version: '3.7'

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=stock
    volumes:
      - stock_pg_data:/bitnami/postgresql

  minio:
    image: quay.io/minio/minio
    container_name: minio
    restart: always
    ports:
      - "9000:9000"
      - "9090:9090"
    environment:
      MINIO_ROOT_USER: brunohp
      MINIO_ROOT_PASSWORD: brunohp3008
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9090"

  minio-setup:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      mc alias set myminio http://minio:9000 admin admin123;
      mc mb myminio/uploads;
      mc policy set public myminio/uploads;
      exit 0;
      "

volumes:
  stock_pg_data:
  minio-data:
